### ISSUE TITLE
Edit Preface

### ISSUE THREAD

**Issue by yurrriq** [idris-hackers/software-foundations#2]
For now, it's copied rather directly from the Coq.

**Comment by steshaw** [comment]
One idea might be to leave some of the SF-in-Coq completely intact (like the Preface). Then introduce a Preface for SF-in-Idris if you like.

**Comment by yurrriq** [comment]
Not a bad idea...

**Comment by langston-barrett** [comment]
Might want to mention Idris here: https://github.com/idris-hackers/software-foundations/blob/fc6fc1ecc4ab5b337f9afe59cd57c0142b454546/src/Preface.lidr#L109

**Comment by yurrriq** [comment]
Closing to simplify tracking on #20.
