### ISSUE TITLE
Give @clayrat commit rights

### ISSUE THREAD

**Issue by yurrriq** [idris-hackers/software-foundations#23]
@jfdm (or anyone else with sufficient permissions), could you please grant commit rights to @clayrat? At this point he's contributing more than I am, and I think it'd be nice if he and I (at least) could trade off reviews and merging.

It would also be good to set the default branch to `develop` (and/or grant me access to the repo settings). Related: #15

Cheers!

**Comment by david-christiansen** [comment]
I just gave @yurrriq admin access and sent a collaborator invite to @clayrat . I'll let @yurrriq do the branch switches :)

**Comment by yurrriq** [comment]
Thank you!

**Comment by clayrat** [comment]
Thanks!

**Comment by yurrriq** [comment]
@clayrat, feel free to open branches on this repo directly, if you like. I've been casually following the [git-flow workflow](http://nvie.com/posts/a-successful-git-branching-model/) using [the AVH edition](https://github.com/petervanderdoes/gitflow-avh/).
