### ISSUE TITLE
Push a release of the first ten chapters

### ISSUE THREAD

**Issue by yurrriq** [idris-hackers/software-foundations#40]
Ideally we can resolve or remove all the `\todo`s, edit the text, format the code (see #39, #24 [`\subsection` hack works], #22, #35 [adopt Iosevka] and maybe #25/#30, et al.)

**Comment by yurrriq** [comment]
I went a little overboard with labeling and such, but now we can track progress with the milestone: https://github.com/idris-hackers/software-foundations/milestone/1

**Comment by clayrat** [comment]
To be honest, I probably won't do most of these issues you've linked. Regarding `todo`s, I think that the text editing should ideally be done by someone more knowing, to avoid misleading people. If you show me how to insert hyperlinks, I could fix those, though. 

So I'm not sure when this release will happen :) In the meantime I'll probably try to finish `IndPrinciples`, make an attempt at splitting `Tactics` and then move on with the new chapters.
