### ISSUE TITLE
PDF is unavailable

### ISSUE THREAD

**Issue by optician** [idris-hackers/software-foundations#53]
A [link](https://idris-hackers.github.io/software-foundations/pdf/sf-idris-2018.pdf) to pdf in README returns 404.

**Comment by yurrriq** [comment]
That link is dependent on https://github.com/idris-hackers/software-foundations/pull/51. Here's [the old PDF](https://idris-hackers.github.io/software-foundations/pdf/sf-idris-2016.pdf), and [the current one](https://github.com/idris-hackers/software-foundations/blob/develop/docs/pdf/sf-idris-2018.pdf).
